# Generated by Django 4.2.3 on 2023-08-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0002_customermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='category',
        ),
    ]
